# Data with populate information and balancing
import pickables
import cards
import mobs


def level_contents(map_no: int):
    content = {1: {"creatures": {"Rat": 12,
                                 "Rat_Warrior": 4,
                                 "Goblin": 1,
                                 },
                   "pickables": {"Dagger": 1,
                                 "Mace": 2,
                                 "LeatherCap": 1,
                                 "HealthPotion": 1,
                                 "HealingRay": 1,
                                 },
                   },

               2: {"creatures": {"Rat": 18,
                                 "Rat_Warrior": 8,
                                 "Goblin": 4,
                                 },
                   "pickables": {"Dagger": 3,
                                 "Mace": 5,
                                 "LeatherCap": 2,
                                 "HealthPotion": 3,
                                 "Fireball": 2,
                                 "HealingRay": 1
                                 },
                   },
               3: {"creatures": {"Rat": 14,
                                 "Rat_Warrior": 8,
                                 "Goblin": 8,
                                 },
                   "pickables": {"Dagger": 3,
                                 "Mace": 5,
                                 "LeatherCap": 3,
                                 "HealthPotion": 4,
                                 "Fireball": 1,
                                 "HealingRay": 1,
                                 "HealthDrain": 1,
                                 },
                   },
               4: {"creatures": {"Rat": 16,
                                 "Rat_Warrior": 12,
                                 "Goblin": 13,
                                 "Lizardmen": 1,
                                 "Lizardmen2": 0,
                                 "RatWarlord": 0,
                                 },
                   "pickables": {"Dagger": 3,
                                 "Mace": 4,
                                 "Helmet": 1,
                                 "HealthPotion": 4,
                                 "LeatherJacket": 2,
                                 "StuddedJacket": 1,
                                 "ChainMail": 0,
                                 "PlateArmour": 0,
                                 "LeatherCap": 3,
                                 "ChainMailHood": 0,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 0,
                                 "LeatherBoots": 3,
                                 "ReinforcedLeatherBoots": 1,
                                 "Sword": 1,
                                 "Axe": 0,
                                 "RustySword": 2,
                                 "Morgenstern": 0,
                                 "DwarvenAxe": 0,
                                 "ElvishBlade": 0,
                                 "ScynthianSword": 0,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 1,
                                 "Poison": 1,
                                 "PoisonedBlade": 1,
                                 "FullRecover": 0,
                                 "PoisonousCloud": 0,
                                 "SacrificeKill": 0,
                                 "PiercingShot": 0,
                                 "PoisoningShot": 0,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               5: {"creatures": {"Rat": 17,
                                 "Rat_Warrior": 14,
                                 "Goblin": 15,
                                 "Lizardmen": 2,
                                 "Lizardmen2": 0,
                                 "RatWarlord": 0,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 0,
                                 "PlateArmour": 0,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 0,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 1,
                                 "Axe": 1,
                                 "RustySword": 4,
                                 "Morgenstern": 0,
                                 "DwarvenAxe": 0,
                                 "ElvishBlade": 0,
                                 "ScynthianSword": 0,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 1,
                                 "Poison": 1,
                                 "PoisonedBlade": 1,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 0,
                                 "SacrificeKill": 0,
                                 "PiercingShot": 0,
                                 "PoisoningShot": 0,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               6: {"creatures": {"Rat": 18,
                                 "Rat_Warrior": 14,
                                 "Goblin": 15,
                                 "Lizardmen": 6,
                                 "Lizardmen2": 0,
                                 "RatWarlord": 0,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 1,
                                 "PlateArmour": 0,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 0,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 2,
                                 "Axe": 1,
                                 "RustySword": 3,
                                 "Morgenstern": 1,
                                 "DwarvenAxe": 0,
                                 "ElvishBlade": 0,
                                 "ScynthianSword": 0,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 2,
                                 "Poison": 1,
                                 "PoisonedBlade": 2,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 1,
                                 "SacrificeKill": 0,
                                 "PiercingShot": 0,
                                 "PoisoningShot": 0,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               7: {"creatures": {"Rat": 14,
                                 "Rat_Warrior": 16,
                                 "Goblin": 18,
                                 "Lizardmen": 12,
                                 "Lizardmen2": 1,
                                 "RatWarlord": 0,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 1,
                                 "PlateArmour": 0,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 0,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 2,
                                 "Axe": 1,
                                 "RustySword": 3,
                                 "Morgenstern": 1,
                                 "DwarvenAxe": 1,
                                 "ElvishBlade": 0,
                                 "ScynthianSword": 0,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 2,
                                 "Poison": 1,
                                 "PoisonedBlade": 2,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 1,
                                 "SacrificeKill": 1,
                                 "PiercingShot": 0,
                                 "PoisoningShot": 0,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               8: {"creatures": {"Rat": 14,
                                 "Rat_Warrior": 15,
                                 "Goblin": 18,
                                 "Lizardmen": 14,
                                 "Lizardmen2": 2,
                                 "RatWarlord": 0,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 1,
                                 "PlateArmour": 1,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 1,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 2,
                                 "Axe": 1,
                                 "RustySword": 3,
                                 "Morgenstern": 1,
                                 "DwarvenAxe": 1,
                                 "ElvishBlade": 1,
                                 "ScynthianSword": 0,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 2,
                                 "Poison": 1,
                                 "PoisonedBlade": 2,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 1,
                                 "SacrificeKill": 1,
                                 "PiercingShot": 1,
                                 "PoisoningShot": 0,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               9: {"creatures": {"Rat": 10,
                                 "Rat_Warrior": 15,
                                 "Goblin": 18,
                                 "Lizardmen": 12,
                                 "Lizardmen2": 7,
                                 "RatWarlord": 1,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 1,
                                 "PlateArmour": 1,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 1,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 2,
                                 "Axe": 1,
                                 "RustySword": 3,
                                 "Morgenstern": 1,
                                 "DwarvenAxe": 1,
                                 "ElvishBlade": 1,
                                 "ScynthianSword": 1,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 2,
                                 "Poison": 1,
                                 "PoisonedBlade": 2,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 1,
                                 "SacrificeKill": 1,
                                 "PiercingShot": 1,
                                 "PoisoningShot": 1,
                                 "PowerfulFireball": 0,
                                 "GlowingBlade": 0,
                                 }

                   },
               10: {"creatures": {"Rat": 10,
                                 "Rat_Warrior": 15,
                                 "Goblin": 18,
                                 "Lizardmen": 12,
                                 "Lizardmen2": 12,
                                 "RatWarlord": 2,
                                 },
                   "pickables": {"Dagger": 4,
                                 "Mace": 6,
                                 "Helmet": 2,
                                 "HealthPotion": 6,
                                 "LeatherJacket": 3,
                                 "StuddedJacket": 2,
                                 "ChainMail": 1,
                                 "PlateArmour": 1,
                                 "LeatherCap": 4,
                                 "ChainMailHood": 1,
                                 "LeatherGloves": 2,
                                 "ChainMailGloves": 1,
                                 "PlateGloves": 1,
                                 "LeatherBoots": 4,
                                 "ReinforcedLeatherBoots": 2,
                                 "Sword": 2,
                                 "Axe": 1,
                                 "RustySword": 3,
                                 "Morgenstern": 1,
                                 "DwarvenAxe": 1,
                                 "ElvishBlade": 1,
                                 "ScynthianSword": 1,
                                 "Fireball": 2,
                                 "HealingRay": 2,
                                 "HealthDrain": 2,
                                 "Poison": 1,
                                 "PoisonedBlade": 2,
                                 "FullRecover": 1,
                                 "PoisonousCloud": 1,
                                 "SacrificeKill": 1,
                                 "PiercingShot": 1,
                                 "PoisoningShot": 1,
                                 "PowerfulFireball": 1,
                                 "GlowingBlade": 1,
                                 }

                   },
               }

    return content[map_no]


def population_dictionary():
    dictionary = {"Rat": mobs.Rat,
                  "Rat_Warrior": mobs.RatWarrior,
                  "Goblin": mobs.Goblin,
                  "Lizardmen": mobs.Lizardmen,
                  "Lizardmen2": mobs.Lizardmen2,
                  "RatWarlord": mobs.RatWarlord,
                  "Dagger": pickables.Dagger,
                  "Mace": pickables.Mace,
                  "Helmet": pickables.Helmet,
                  "HealthPotion": pickables.HealthPotion,
                  "LeatherJacket": pickables.LeatherJacket,
                  "StuddedJacket": pickables.StuddedJacket,
                  "ChainMail": pickables.ChainMail,
                  "PlateArmour": pickables.PlateArmour,
                  "LeatherCap": pickables.LeatherCap,
                  "ChainMailHood": pickables.ChainMailHood,
                  "LeatherGloves": pickables.LeatherGloves,
                  "ChainMailGloves": pickables.ChainMailGloves,
                  "PlateGloves": pickables.PlateGloves,
                  "LeatherBoots": pickables.LeatherBoots,
                  "ReinforcedLeatherBoots": pickables.ReinforcedLeatherBoots,
                  "Sword": pickables.Sword,
                  "Axe": pickables.Axe,
                  "RustySword": pickables.RustySword,
                  "Morgenstern": pickables.Morgenstern,
                  "DwarvenAxe": pickables.DwarvenAxe,
                  "ElvishBlade": pickables.ElvishBlade,
                  "ScynthianSword": pickables.ScynthianSword,
                  "Fireball": cards.Fireball,
                  "HealingRay": cards.HealingRay,
                  "HealthDrain": cards.HealthDrain,
                  "Poison": cards.Poison,
                  "PoisonedBlade": cards.PoisonedBlade,
                  "FullRecover": cards.FullRecover,
                  "PoisonousCloud": cards.PoisonousCloud,
                  "SacrificeKill": cards.SacrificeKill,
                  "PiercingShot": cards.PiercingShot,
                  "PoisoningShot": cards.PoisoningShot,
                  "PowerfulFireball": cards.PowerfulFireball,
                  "GlowingBlade": cards.GlowingBlade,
                  }
    return dictionary
